language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t moody1 .

script:
  - docker run -e CI=true moody1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "MoodyReact"
  env: "MoodyReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-605959340483"
  bucket_path: "MoodyReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

